enum ErrorCode {
  INVALID_PARAMETERS = "INVALID_PARAMETERS",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  NOT_FOUND = "NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",
}

export default ErrorCode
