services:
  react-ssr:
    build: .
    command: npm start
    environment:
      - PORT=4000
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
    ports:
      - 4000:4000
